name: OpenWrt Release Package

on:
  workflow_call:
    inputs:
      artifact_pattern:
        required: true
        type: string
      tag_name:
        required: true
        type: string
    secrets:
      RELEASE_TOKEN:
        required: true

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v6
        with:
          pattern: ${{ inputs.artifact_pattern }}
          path: ${{ github.workspace }}/release-assets/
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name }}
          files: ${{ github.workspace }}/release-assets/*.ipk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Summary
        run: |
          echo "## Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Tag**: ${{ inputs.tag_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Files**: $(ls ${{ github.workspace }}/release-assets/*.ipk | wc -l)" >> $GITHUB_STEP_SUMMARY
