name: Reusable Release

on:
  workflow_call:
    inputs:
      artifact_pattern:
        description: 'Pattern to find the artifacts from build jobs (e.g. package-name-*)'
        required: true
        type: string
      release_file_pattern:
        description: 'Pattern for files to include in the release (e.g. *.ipk)'
        required: false
        type: string
        default: '*.[ia]pk'
      tag_name:
        required: true
        type: string
      draft:
        required: true
        type: boolean
        default: false
    secrets:
      RELEASE_TOKEN:
        required: true

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: ${{ inputs.artifact_pattern }}
          path: ${{ github.workspace }}/release-assets/
          merge-multiple: true

      - name: Create Changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          tag: ${{ inputs.tag_name }}
          reverseOrder: true
          excludeTypes: other,doc,chore,refactor,format,debug,bump

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ inputs.tag_name }}
          files: ${{ github.workspace }}/release-assets/${{ inputs.release_file_pattern }}
          generate_release_notes: true
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.RELEASE_TOKEN }}
          draft: ${{ inputs.draft }}
