name: Reusable Release

on:
  workflow_call:
    inputs:
      artifact_pattern:
        description: 'Pattern to find the artifacts from build jobs (e.g. package-name-*)'
        required: true
        type: string
      release_file_pattern:
        description: 'Pattern for files to include in the release (e.g. *.ipk)'
        required: false
        type: string
        default: '*.ipk'
      tag_name:
        required: true
        type: string
    secrets:
      RELEASE_TOKEN:
        required: true

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v6
        with:
          pattern: ${{ inputs.artifact_pattern }}
          path: ${{ github.workspace }}/release-assets/
          merge-multiple: true

      - name: Create Changelog (2)
        id: changelog_second
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Debug
        run: |
          echo "${{ steps.changelog_second.outputs.changes }}"

      - name: Create Changelog (3)
        id: changelog_third
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          tag: ${{ inputs.tag_name }}

      - name: Debug
        run: |
          echo "${{ steps.changelog_third.outputs.changes }}"

      - name: Create Changelog (1)
        uses: Helmisek/conventional-changelog-generator@v1.0.6-release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name }}
          files: ${{ github.workspace }}/release-assets/${{ inputs.release_file_pattern }}
          generate_release_notes: true
          body: ${{ steps.changelog_second.outputs.changes }} ${{ steps.changelog_third.outputs.changes }}
          token: ${{ secrets.RELEASE_TOKEN }}
